version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    env_file: ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U biocad" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npm run migrate:deploy && npm run dev"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres-data: